### ISSUE TITLE
Need to document how Behavior and soundcard ports are determined and set in Settings_box.csv

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#125]

**Comment by XX-Yin** [comment]
@ellahiltonvano We previously had a mapping between USB ports and behavior and sound card ports. Tiffany helped fixed each computer USB ports (Otherwise, the USB port shown in your computer will change even if you plug it into the same physical USB port). 

For the upcoming update, we need to assign behavior and sound cards to computer ports and fix these physical port.

**Comment by ellahiltonvano** [comment]
Great. I do not know how to do this, could Xinxin and Han work on this when setting up computers?

**Comment by XX-Yin** [comment]
Tiffany helped fixed these physical ports. We should ask Tiffany to help with this process. Do anyone know Tiffany's Github account?

**Comment by alexpiet** [comment]
- resolved in #138
