### ISSUE TITLE
Autosave: should save data every ? trials

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#196]
- Instead of saving all of the data at the end of the session, we should save data every ? number of trials
- This should happen in a thread to prevent stalling trials, and we should measure inter-trial variability to ensure this is true
- The interval of trials to save should be determined by the practical constraints of saving

**Comment by alexpiet** [comment]
I discussed this with Jeremiah. We reasoned that <1% data loss in the training room is probably ok (not great, but acceptable). Data loss during ephys recordings would not be. We think that the Harp messages are being logged and we can always try to reconstruct data if needed. We decided to hold off on this until we get 446 up and running and the new motor stages, then we can evaluate how often the session is crashing

**Comment by yonibrowning** [comment]
I am reviving this thread. We lost an ephys session last week and so want to roll out a solution to this before we loose any more.

I think it makes the most sense to save data at the end of each trial. Because data arrays must, by necessity, grow on each trial, the safest thing is probably going to be writing trials one at a time and recombine at the end- that way sessions can go on forever without increasing saving load. We can do validation to confirm that this can be reconstructed exactly into the existing format. 

In interest of getting something working before we do much more ephys, its probably easiest to start with a non-threaded version of this and work our way up to thread-safe version in the next iteration. I can take a stab a solution this week.

**Comment by alexpiet** [comment]
@yonibrowning Thanks for taking this issue on.

I would recommend appending each trial to a file, rather than creating individual files for each trial. That way no reconstruction is necessary. 

I would also investigate what information is currently being logged from the Harp messages - it might be easier just to implement a function to recover lost data from the Harp logs. 

What rig/time did you lose an ephys session? is the underlying issue documented?

**Comment by yonibrowning** [comment]
I have created a pull request to address this here: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/484

At present, I opted for many small files because I do not know of a safe way to continuously write to a json. This could easily be changed if someone has a preferred format. 

As to your other comments:
Harp logs won't have task state information, will they? They are better than nothing but not complete...

Our loss was on rig 2, the cause was disconnecting a harp device during a session (read "user error"). "Force save" did not work and the session couldn't complete with bonsai stopped, so we lost the data.

**Comment by alexpiet** [comment]
I didn't know anyone was running the task on ephys rig 2. Can you please enable automatic daily updates, install openssh server, and tell me the hostname so I can hook that rig into our system for tracking errors?

**Comment by yonibrowning** [comment]
> I didn't know anyone was running the task on ephys rig 2. Can you please enable automatic daily updates, install openssh server, and tell me the hostname so I can hook that rig into our system for tracking errors?

Long term yes, but I don't think we can in the short term. We have been piloting a breathing sensor that talks to bonsai on there, and until the code this sensor makes its way into the production repos I worry it will break with every auto update? If there is a way to do this then we can reconsider - it is all bonsai code (the passive sensor doesn't talk to the Gui at all), so one valid option might be to temporarily link to non-updating bonsai workflow? 

I'll create a separate issue to discuss.
