### ISSUE TITLE
Json -> nwb errors

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/dynamic-foraging-task#271]
- [x] 2024-03-01 17:55:41 __main__ ERROR [batch_convert_json_to_nwb]: Error converting 713557_2024-02-06_11-36-59.json to .nwb: list index out of range
       - An edge case where obj has B_NewscalePositions but it's empty
- [x] 2024-03-01 17:56:02 __main__ ERROR [batch_convert_json_to_nwb]: Error converting 710414_2024-02-12_14-26-37.json to .nwb: could not resolve dtype for VectorData 'animal_response'
       - no trial
- [x] 707254_2024-02-16_13-18-41.json to .nwb: type object 'obj' has no attribute 'TP_BaseRewardSum'
       - I don't understand this. This json file does not have any TP_fields... @XX-Yin
[707254_2024-02-16_13-18-41.json](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/files/14467738/707254_2024-02-16_13-18-41.json)
- [x] Error converting 707254_2024-02-09_13-02-33.json to .nwb: type object 'obj' has no attribute 'B_TrialEndTime' 
      - Empty file

**Comment by XX-Yin** [comment]
"707254_2024-02-16_13-18-41.json to .nwb: type object 'obj' has no attribute 'TP_BaseRewardSum'
- I don't understand this. This json file does not have any TP_fields" 

Hi Han, I checked this session. I think it's because the user loaded a session and then directly saved the session. In this case, there is no `TP_` data, but the `B_` data is still here.
