### ISSUE TITLE
Main branch is not protected

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#38]
The main branch should be protected against commits. Changes should only be made through reviewed pull requests

**Comment by jsiegle** [comment]
These are the current `main` branch protections. Should we add something else?

<img width="813" alt="Screen Shot 2023-11-11 at 10 45 59 AM" src="https://github.com/AllenNeuralDynamics/dynamic-foraging-task/assets/200366/b0aa7e88-fce5-48de-8252-6888a48c9d9d">

**Comment by alexpiet** [comment]
@jsiegle Did you just update those settings? They look good to me. The main issue I was concerned about was @XX-Yin has been committing straight to the main branch. This is understandable because he has been doing rapid development work, but as more people join code development we should transition to a more orderly process with pull requests and approvals. 

@hanhou @XX-Yin @bruno-f-cruz Any thoughts?

**Comment by jsiegle** [comment]
I guess that's because admins can bypass the pull request requirement – Xinxin should just make sure to use PRs for future changes

**Comment by XX-Yin** [comment]
I agree with this. Will do!
---- Replied Message ----
From Josh Siegle ***@***.***> Date 11/11/2023 15:27 To AllenNeuralDynamics/dynamic-foraging-task ***@***.***> Cc XX-Yin ***@***.***>,
Mention ***@***.***> Subject Re: [AllenNeuralDynamics/dynamic-foraging-task] Main branch is not protected (Issue #38)  

I guess that's because admins can bypass the pull request requirement – Xinxin should just make sure to use PRs for future changes
