### ISSUE TITLE
Redundant functions?

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#54]
I've noticed there are functions that appear to be redundant. Possible result of development versioning that wasn't cleaned up. For example in `Foraging.py` we have `_StartTrialLoop` and `_StartTrialLoop1`. We should removed depreciated functions to reduce maintenance costs, and increase clarity of code.

**Comment by alexpiet** [comment]
- It appears that both `StartTrialLoop1` and `StartTrialLoop` are both called. It is unclear to me what these functions are doing and why they are so similar. @XX-Yin can you clarify?

**Comment by XX-Yin** [comment]
We only call StartTrialLoop in the current code. The difference is that the "figure update", "generate a trial" and "get animal response" all run in separate threads. However, in StartTrialLoop, only the "get animal response" is running in a separate thread and other functions are running in the main thread. The main reason for using multithreading is that the visualization does not affect trial propagation. I found that the limiting factor was just "get animal response", so used StartTrialLoop instead of StartTrialLoop1.

**Comment by XX-Yin** [comment]
We can keep StartTrialLoop1 for now. We may use this in the future when visualizations become more complex.
