### ISSUE TITLE
double outputs in the console and GUI stalls

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#866]
Timestamps in the GUI were duplicated. And the GUI got stuck in the middle of the session.

[W10DT713883-A_gui_log_2024-10-30_11-47-25.txt](https://github.com/user-attachments/files/17579761/W10DT713883-A_gui_log_2024-10-30_11-47-25.txt)

**Comment by alexpiet** [comment]
Did this happen more than once? It looked like you ran several sessions before the duplicate outputs started

**Comment by XX-Yin** [comment]
I ran one successful session before this failure session.

**Comment by alexpiet** [comment]
Key points in this session:
12:03:46 PM:INFO:Foraging:Foraging.py:log_session:line 4198:Starting log file at D:\BehaviorData\323_EPHYS3\0\behavior_0_2024-10-30_12-03-46\behavior
- 3 trials run

12:04:16 PM:INFO:Foraging:Foraging.py:log_session:line 4198:Starting log file at D:\BehaviorData\323_EPHYS3\0\behavior_0_2024-10-30_12-04-16\behavior
- 19 trials run

12:17:26 PM:INFO:Foraging:Foraging.py:log_session:line 4198:Starting log file at D:\BehaviorData\323_EPHYS3\744330\behavior_744330_2024-10-30_12-17-20\behavior
- double timestamps start immediately, most likely an issue with how the last session ended and is probably just a logging error
- 531 trials run

01:52:54 PM:INFO:Foraging:Foraging.py:log_session:line 4198:Starting log file at D:\BehaviorData\323_EPHYS3\744331\behavior_744331_2024-10-30_13-52-49\behavior
- 302 trials
- 02:40:33 PM:INFO:Foraging:Foraging.py:_Save:line 2511:saving canceled by user
- no more trials are generated
- 03:02:20 PM:INFO:Foraging:Foraging.py:_Save:line 2491:Saving current session, ForceSave=True
- everything saves and you close, no data was lost

I think there are two things happening here.
- The double timestamps are probably because a logger didn't get closed properly @micahwoodard do you have any insight here? Unless we know the problem, I suspect we should wait to see if it happens again
- for some reason saving was cancelled by the user, which cause the session to stall. This seems impossible to debug, since we dont know what the trigger was.

as an aside its very difficult to look at this logs with the camera verbose level set so high.

**Comment by XX-Yin** [comment]
We should disable the camera verbose. It's almost useless

**Comment by alexpiet** [comment]
> We should disable the camera verbose. It's almost useless

You can do this on your rig by changing the codec: add `-v 24` to the codec in `Settings_box#.csv`. This was changed to the default in the settings template in this PR: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/587

**Comment by ellahiltonvano** [comment]
@XX-Yin let me know when you've completed this in your rig and we can close the issue

**Comment by XX-Yin** [comment]
I didn't see this yesterday. We can temporarily close this issue. I will reopen it if I see it again
